apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-example
  namespace: tesco
  labels:
    app: rest-example
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-example
      tier: backend
  template:
    metadata:
      labels:
        app: rest-example
        tier: backend
    spec:
      containers:
      - name: rest-example
        image: kubernetes/rest-example:0.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: env.hello.message
            valueFrom:
              configMapKeyRef:
                name: tesco-config
                key: env.hello.message
