apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-example
  labels:
    app: rest-example
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-example
      tier: backend
  template:
    metadata:
      labels:
        app: rest-example
        tier: backend
    spec:
      containers:
      - name: rest-example
        image: kubernetes/rest-example:0.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
