apiVersion:  v1
kind: Service
metadata:
  name: rest-example   
spec:
  selector:    
    app: rest-example    
    tier: backend   
  type: LoadBalancer 
  ports:
    - port: 8888
      targetPort: 8080
  selector:
    app: rest-example
    tier: backend