version: '3'
services:
  db:
    image: tdevs/h2:1.0.0
    ports:
      - "9092:9092"
  data:
    image: tdevs/users-data:1.0.0
    volumes:
      - /d/Szkolenia/Jug/dockub/codebase/docker/04-compose/conf/data:/conf
    links:
      - db
  api:
    image: tdevs/users-api:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - /d/Szkolenia/Jug/dockub/codebase/docker/04-compose/conf/api:/conf
    links:
      - data
